brew 'bat'
brew 'bitwarden-cli'
brew 'chezmoi'
brew 'eza'
brew 'gh'
brew 'ripgrep'
brew 'starship'
brew 'volta'
# brew 'fd'
# brew 'ffmpeg'
# brew 'fx'
# brew 'rsync'
# brew 'yt-dlp'

# GPG
brew 'gnupg'
tap 'jorgelbg/tap'
brew 'pinentry-mac'
brew 'jorgelbg/tap/pinentry-touchid'

# cask 'android-file-transfer'
cask 'arc'
cask 'amazon-q'
cask 'battle-net'
# cask 'calibre'
cask 'discord'
cask 'docker'
cask 'figma'
cask 'firefox'
cask 'font-jetbrains-mono-nerd-font'
cask 'google-chrome'
cask 'iterm2'
cask 'keka'
#cask 'kekaexternalhelper'
cask 'megasync'
cask 'obsidian'
cask 'qbittorrent'
cask 'raycast'
cask 'readdle-spark'
# cask 'slack'
cask 'steam'
cask 'telegram'
cask 'ticktick'
cask 'vlc'
cask 'webstorm'
# cask 'balenaetcher'
# cask 'crossover'
# cask 'MonitorControl'
# cask 'homebrew/cask-drivers/logitech-g-hub' # 100% CPU usage on Intel Macs

#mas 'Balance Lock', id: 1019371109
mas 'Bitwarden', id: 1352778147
mas 'Unsplash Wallpapers', id: 1284863847
mas 'MEGA VPN', id: 6456784858
mas 'Windows App', id: 1295203466
