alias pn="pnpm"
alias cat="bat"
alias grep="rg --smart-case --context 4"
alias rg="rg --smart-case --context 4"
alias ls="eza --all --group-directories-first --icons --color=always --git-ignore"
alias l="eza --all --group-directories-first --icons --color=always --git-ignore --long --git"
alias ll="eza --all --group-directories-first --icons --color=always --git-ignore --long --git"
alias lg="eza --all --group-directories-first --icons --color=always"
alias llg="eza --all --group-directories-first --icons --color=always --long --git"
alias grbi="git rebase --interactive --committer-date-is-author-date"
